name: Update Cargo.toml on -rs tag

on:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  update-cargo:
    runs-on: ubuntu-latest
    name: Update Cargo.toml when tag ends with -rs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Get tag name
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Update Cargo.toml if tag ends with -rs
        run: |
          TAG="${{ steps.tag.outputs.tag }}"
          echo "Detected tag: $TAG"
          # Normalize: strip leading 'v' if present
          NORM=${TAG#v}
          if [[ "$NORM" == *-rs ]]; then
            echo "Tag ends with -rs, updating Cargo.toml"
            echo "Updating version.txt"
            echo -n "$TAG" > version.txt
            FILE=Cargo.toml
            if [ ! -f "$FILE" ]; then
              echo "$FILE not found, aborting" >&2
              exit 1
            fi

            # Update the first 'version = "..."' occurrence in [package] section
            awk -v ver="${NORM}" '
              BEGIN{in_pkg=0; replaced=0}
              /^\[package\]/{in_pkg=1; print; next}
              /^\[/{ if(in_pkg && !/^\[package\]/){ in_pkg=0 } }
              { if(in_pkg && !replaced && $0 ~ /^version[[:space:]]*=/){
                    print "version = \"" ver "\""; replaced=1; next
                }
                print
              }
            ' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"

            if git status --porcelain | grep -q "rust/Cargo.toml"; then
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git add Cargo.toml
              git add version.txt
              git commit -m "Update Cargo.toml version to ${NORM}"
              git push origin rust
              echo "Cargo.toml updated and pushed"
            else
              echo "No changes detected in Cargo.toml"
            fi
          else
            echo "Tag does not end with -rs; skipping"
          fi
