name: Update version.txt and create tag from commit message

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  update-version-and-tag:
    name: Update version.txt and tag when head commit message ends with -py (single-line, no spaces)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Read head commit message and SHA
        id: head
        shell: bash
        run: |
          set -euo pipefail
          # GITHUB_SHA points to the head commit of the push
          SHA="${GITHUB_SHA}"
          MSG="$(git log -1 --pretty=%B "$SHA")"
          echo "commit_sha=$SHA" >> "$GITHUB_OUTPUT"
          # Use a multiline output for message to preserve exact content
          {
            echo 'commit_message<<EOF'
            printf '%s\n' "$MSG"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Update version.txt on python branch and create/push tag
        id: update
        shell: bash
        run: |
          set -euo pipefail
          MSG='${{ steps.head.outputs.commit_message }}'
          SHA='${{ steps.head.outputs.commit_sha }}'

          # Determine if commit message is valid: single line, no whitespace, ends with -py
          FIRST_LINE="$(printf '%s' "$MSG" | head -n1)"
          # Count logical lines robustly: append a trailing newline when counting
          # so a single-line message without a trailing newline counts as 1.
          LINE_COUNT="$(printf '%s\n' "$MSG" | wc -l | tr -d ' ')"

          echo "Head commit SHA: $SHA"
          echo "Head commit first line: $FIRST_LINE"
          echo "Total message lines: $LINE_COUNT"

          # Check: one line only
          if [ "$LINE_COUNT" != "1" ]; then
            echo "Commit message is not a single line, skipping."
            exit 0
          fi

          # Check: ends with -py
          if [[ "$FIRST_LINE" != *-py ]]; then
            echo "Commit message does not end with -py, skipping."
            exit 0
          fi

          # Check: contains no whitespace characters (space, tab, etc.)
          if echo "$FIRST_LINE" | grep -q '[[:space:]]'; then
            echo "Commit message contains whitespace, skipping."
            exit 0
          fi

          VERSION="$FIRST_LINE"
          echo "Version detected from commit message: $VERSION"

          # Update version.txt on python branch
          git fetch --no-tags origin python
          git checkout -B python origin/python || git checkout python
          git pull --ff-only origin python || true

          echo -n "$VERSION" > version.txt

          if git status --porcelain | grep -q "^ M version.txt\|^\?\? version.txt"; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add version.txt
            git commit -m "Update version.txt to $VERSION"
            git push origin python
            echo "version.txt updated and pushed to python"
          else
            echo "version.txt unchanged on python branch; nothing to commit"
          fi

          # Create tag on the pushed commit (not the python branch commit)
          git fetch --tags origin || true
          if git rev-parse -q --verify "refs/tags/$VERSION" >/dev/null || \
             git ls-remote --exit-code --tags origin "$VERSION" >/dev/null 2>&1; then
            echo "Tag $VERSION already exists on local or remote; skipping creation."
          else
            git tag -a "$VERSION" "$SHA" -m "$VERSION"
            git push origin "refs/tags/$VERSION"
            echo "Created and pushed tag $VERSION at $SHA"
          fi

          # Expose version for downstream steps
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Install packaging dependencies (fpm + rpm)
        if: steps.update.outputs.version != ''
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential rpm
          sudo gem install --no-document fpm

      - name: Build .deb and .rpm with fpm
        if: steps.update.outputs.version != ''
        shell: bash
        run: |
          set -euo pipefail
          chmod +x packaging/build_packages.sh
          packaging/build_packages.sh

      - name: Create GitHub Release and upload assets
        if: steps.update.outputs.version != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.update.outputs.version }}
          name: ${{ steps.update.outputs.version }}
          files: |
            packaging/dist/*